### ISSUE TITLE
Bahmni offline sync code has a minor typo that is causing openmrs to fail on load

### ISSUE THREAD

**Issue by buvaneswari-arun** [Bahmni/bahmni-offline-sync#9]
+Problem : +

Today after installing Bahmni connect on Bahmni version 0.92 , open mr fails to startup.

Analysis : 

This is how the log looks,

Unable to start OpenMRS. Error thrown was: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventRecordServiceHelper' defined in URL [jar:file:/opt/openmrs/.openmrs-lib-cache/bahmniOfflineSync/bahmniOfflineSync.jar!/org/bahmni/module/bahmniOfflineSync/utils/EventRecordServiceHelper.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.bahmni.module.bahmniOfflineSync.utils.EventRecordServiceHelper]: Constructor threw exception; nested exception is java.lang.NullPointerException
org.openmrs.module.ModuleException: Unable to start OpenMRS. Error thrown was: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventRecordServiceHelper' defined in URL [jar:file:/opt/openmrs/.openmrs-lib-cache/bahmniOfflineSync/bahmniOfflineSync.jar!/org/bahmni/module/bahmniOfflineSync/utils/EventRecordServiceHelper.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.bahmni.module.bahmniOfflineSync.utils.EventRecordServiceHelper]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.openmrs.web.WebDaemon.startOpenmrs(WebDaemon.java:65)
	at org.openmrs.web.Listener.contextInitialized(Listener.java:196)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4751)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5175)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
On looking into the code I found this ,

https://github.com/Bahmni/bahmni-offline-sync/blob/BAH-992/omod/src/main/java/org/bahmni/module/bahmniOfflineSync/utils/EventRecordServiceHelper.java#L131

There is a space in between `AtomFeedSpringTransactionManager .class` that is causing the issue. To test the theory I removed the space did a local build and deployed to confirm.
This issue exists on all versions of code beyond .91 so probably a hotfix for .92 and fix on the master would be required.

**Comment by rajeshkumarwf** [comment]
I can work on this

**Comment by buvaneswari-arun** [comment]
kindly post pull request details
